# ==========================
# IA
# ==========================
email.summary.ai.enabled=true
email.summary.ai.provider=gemini

# ==========================
# Google Gemini
# ==========================
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# ==========================
# Email Summary
# ==========================
email.summary.destination=${EMAIL_SUMMARY_DESTINATION}

# ==========================
# Logs
# ==========================
logging.file.name=logs/email-summary.log
logging.level.root=INFO
logging.level.com.samara.emailsummary=INFO